sudo: required
dist: trusty
language: python
python:
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - pip install pip
  - pip install pipenv
install: pipenv install --deploy
script: pytest -v twpm tests
notifications:
  email: true
    on_success: change
    on_failure: always
