name: CI

on:
  push:
    branches: [main]

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python environment with Pipenv
        run: |
          python3 -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run mypy-runner
        run: ./bin/mypy-runner

      - name: Run pytest-runner
        run: ./bin/pytest-runner

      - name: Run pylint-runner
        run: ./bin/pylint-runner

      - name: Run yapf-linter
        run: ./bin/yapf-linter

      - name: Run isort-linter
        run: ./bin/isort-linter
