name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Python environment with Pipenv
        run: |
          python3 -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run mypy-runner
        run: pipenv run ./bin/mypy-runner

      - name: Run pylint-runner
        run: pipenv run ./bin/pylint-runner

      - name: Run yapf-linter
        run: pipenv run ./bin/yapf-linter

      - name: Run isort-linter
        run: pipenv run ./bin/isort-linter

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Python environment with Pipenv
        run: |
          python3 -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run pytest-runner
        run: pipenv run ./bin/pytest-runner
